# Generated by Django 5.2.4 on 2025-12-01 08:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('document_type', models.CharField(choices=[('txt', 'Text File'), ('pdf', 'PDF Document'), ('docx', 'Word Document')], max_length=10)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('original_text', models.TextField(blank=True)),
                ('braille_text', models.TextField(blank=True)),
                ('is_translated', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
