# Generated by Django 5.2.3 on 2026-01-04 11:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braille_translator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrailleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='braille_images/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('braille_text', models.TextField(blank=True)),
                ('translated_text', models.TextField(blank=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
