# Generated by Django 6.0.1 on 2026-03-18 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('braille_translator', '0002_brailleimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={},
        ),
        migrations.RemoveField(
            model_name='brailleimage',
            name='processing_notes',
        ),
    ]
